// Generated by pnpm leads:reconcile --apply. Do not edit by hand.

export type SubmissionType = "booking" | "contact";

export interface Submission {
  id: string;
  type: SubmissionType;
  name: string;
  email: string;
  phone?: string;
  date: string;
  message?: string;
  arrival?: string;
  departure?: string;
  guests?: string;
  pagePath?: string;
  referral?: string;
  referrer?: string;
  sourceForm?: string;
}

export const submissionImportSummary = {
  "exportedAt": "2026-09-02T23:57:44.000Z",
  "rawRows": 40,
  "visibleRows": 20,
  "filteredRows": 20,
  "contactRows": 21,
  "bookingRows": 19,
  "excludedEmailCaptureRows": 2,
  "reviewRows": 0,
  "sourceFiles": [
    "Formspree API xvzarybk contact complete export",
    "Formspree API xqeqllek booking complete export"
  ]
} as const;

export const submissions: Submission[] = [
  {
    "id": "b-20260830-katie-gump",
    "type": "booking",
    "name": "Katie Gump",
    "email": "gumpkatie@gmail.com",
    "phone": "+1 330-240-4404",
    "date": "2026-08-30T23:09:35.000Z",
    "arrival": "2027-03-13",
    "departure": "2027-03-20",
    "guests": "8 adults, 1 child",
    "message": "Main House. Returning guest. friend hang out; secret beach; snorkel; possible dives? Hi Gil! Hi Consi!",
    "pagePath": "/book",
    "referral": "returning-guest",
    "referrer": "https://www.google.com/",
    "sourceForm": "booking"
  },
  {
    "id": "c-20260805-sue-rob-keller",
    "type": "contact",
    "name": "Sue & Rob Keller",
    "email": "skuck2011@gmail.com",
    "date": "2026-08-05T23:18:49.681Z",
    "message": "Hello Gil & Consi!\nHow are you?\n\nI know we just saw you guys in March when we were there with Trent & Sonja but we want to come back and see you in 2027!\n\nRob & I would like to bring two new couples to the island.....we are thinking February 20th to the 27th. Can you tell me if the villa is available that week?\n\nIt would be 3 couples (total of 6 adults) and two young kids (ages 11 & 9) so we would utilize the bunk room for them.\n\nLooking forward to hearing back from you soon! Thank you!\n\nSue",
    "pagePath": "/contact",
    "referrer": "https://www.google.com/",
    "sourceForm": "contact"
  },
  {
    "id": "b-20260706-grace-barfield",
    "type": "booking",
    "name": "Grace Barfield",
    "email": "grace@foundluxurytravel.com",
    "phone": "+1 713-553-4033",
    "date": "2026-07-06T21:56:27.188Z",
    "arrival": "2026-12-21",
    "departure": "2026-12-28",
    "guests": "1 adult",
    "message": "Honeymoon",
    "pagePath": "/book",
    "referral": "google",
    "sourceForm": "booking"
  },
  {
    "id": "b-20260627-carla-sears",
    "type": "booking",
    "name": "Carla Sears",
    "email": "goodjobgoodjob@bellsouth.net",
    "phone": "+1 205-222-4118",
    "date": "2026-06-27T17:45:01.419Z",
    "arrival": "2026-12-12",
    "departure": "2026-12-19",
    "guests": "8 adults",
    "message": "golf cart for stay service to and from the airport",
    "pagePath": "/book",
    "referral": "other-search",
    "referrer": "https://www.google.com/",
    "sourceForm": "booking"
  },
  {
    "id": "b-20260613-lyles-eddins",
    "type": "booking",
    "name": "Lyles Eddins",
    "email": "virginialyles@gmail.com",
    "phone": "+1 704-458-5634",
    "date": "2026-06-13T18:08:32.773Z",
    "arrival": "2027-03-19",
    "departure": "2027-03-25",
    "guests": "4 adults, 4 children ages 13 and 17",
    "message": "Family trip",
    "pagePath": "/book",
    "referral": "other-search",
    "sourceForm": "booking"
  },
  {
    "id": "c-20260603-natalie-peterson",
    "type": "contact",
    "name": "Natalie Peterson",
    "email": "nataliempeterson@gmail.com",
    "date": "2026-06-03T10:51:52.610Z",
    "message": "Hello! We are a group of 6 women traveling from different parts of the US to celebrate our 50th birthdays next year. We are looking to travel February 11-15, 2027. I would appreciate to hear estimates of the rates/costs for us at that time please. What is included and how do you estimate extra costs such as groceries and excursions pls? Thank you!",
    "pagePath": "/",
    "referrer": "https://www.google.com/",
    "sourceForm": "contact"
  },
  {
    "id": "c-20260601-bryant-craig",
    "type": "contact",
    "name": "Bryant Craig",
    "email": "craigdvm@gmail.com",
    "date": "2026-06-01T12:25:53.860Z",
    "message": "I have sent several booking requests and called last week. Just checking to see what the status of my request is currently. They were sent with the email craigdvm@gmail.com, you can send directly back to that email or call me at 580-541-7004 Bryant Craig",
    "pagePath": "/contact",
    "referrer": "https://www.canarycove.com/book",
    "sourceForm": "contact"
  },
  {
    "id": "b-20260526-bryant-craig",
    "type": "booking",
    "name": "Bryant Craig",
    "email": "craigdvm@gmail.com",
    "phone": "+1 580-541-7004",
    "date": "2026-05-26T15:39:23.247Z",
    "arrival": "2026-09-12",
    "departure": "2026-09-19",
    "guests": "6 adults",
    "message": "We will have 6 for the majority of the stay but might just have 2-4 for part of it.",
    "pagePath": "/book",
    "referral": "other",
    "referrer": "https://www.bing.com/",
    "sourceForm": "booking"
  },
  {
    "id": "b-20260525-cyndra-crossman",
    "type": "booking",
    "name": "Cyndra Crossman",
    "email": "cyndra.rae@yahoo.com",
    "phone": "+1 602-503-1919",
    "date": "2026-05-25T23:56:59.135Z",
    "arrival": "2027-01-28",
    "departure": "2027-02-02",
    "guests": "12 adults, 1 child age 4",
    "message": "40th birthday celebration Not exactly sure how many people but maybe 10-12?",
    "pagePath": "/book",
    "referral": "google",
    "referrer": "https://www.google.com/",
    "sourceForm": "booking"
  },
  {
    "id": "c-20260520-bryant-craig",
    "type": "contact",
    "name": "Bryant Craig",
    "email": "craigdvm@gmail.com",
    "date": "2026-05-20T15:03:09.939Z",
    "message": "We are looking to book for September 11th to the 18th, can you let us know if this is available?",
    "pagePath": "/contact",
    "referrer": "https://www.bing.com/",
    "sourceForm": "contact"
  },
  {
    "id": "b-20260516-bryant-craig",
    "type": "booking",
    "name": "Bryant Craig",
    "email": "craigdvm@gmail.com",
    "phone": "+1 580-541-7004",
    "date": "2026-05-16T13:18:46.038Z",
    "arrival": "2026-09-12",
    "departure": "2026-09-19",
    "guests": "4 adults",
    "message": "Slow pace- fishing, snorkeling, sight seeing",
    "pagePath": "/book",
    "referral": "other",
    "referrer": "https://duckduckgo.com/",
    "sourceForm": "booking"
  },
  {
    "id": "b-20260502-bryant-craig",
    "type": "booking",
    "name": "Bryant Craig",
    "email": "craigdvm@gmail.com",
    "phone": "+1 580-541-7004",
    "date": "2026-05-02T15:45:08.185Z",
    "arrival": "2026-09-13",
    "departure": "2026-09-19",
    "guests": "6 adults",
    "message": "Relax and fun with friends. Will want to snorkel a little and one or more will want to do a couple days of fishing with a guide.",
    "referral": "other",
    "sourceForm": "booking"
  },
  {
    "id": "b-20260429-blade-cruickshank",
    "type": "booking",
    "name": "Blade Cruickshank",
    "email": "blade.cruickshank@gmail.com",
    "phone": "+1 405-434-8827",
    "date": "2026-04-29T19:23:57.943Z",
    "arrival": "2026-10-31",
    "departure": "2026-11-07",
    "guests": "6 adults",
    "message": "Hi Canary Cove Team! I'm so excited to try and coordinate a trip to come back. We are looking at 3 couples. We will probably do snorkeling and maybe a fishing day and day or two in town. We are considering renting a golf cart to explore a few spots but maybe only a couple of the days.",
    "referral": "other",
    "sourceForm": "booking"
  },
  {
    "id": "c-20260429-val-kaye",
    "type": "contact",
    "name": "Val Kaye",
    "email": "val@sisterhoodtravels.com",
    "date": "2026-04-29T16:29:36.962Z",
    "message": "Hello, this is my 3rd email request for a reach out for information to book your establishment and I have not heard back from anyone. I have called both phone numbers and no answer. I am hoping to get some information from you for our group. If someone could please replay I would appreciate it. Thank you, Val Kaye",
    "sourceForm": "contact"
  },
  {
    "id": "b-20260427-jon-kurtyka",
    "type": "booking",
    "name": "Jon Kurtyka",
    "email": "jonkurtyka@yahoo.com",
    "phone": "+1 215-292-1040",
    "date": "2026-04-27T15:46:02.589Z",
    "arrival": "2026-05-21",
    "departure": "2026-05-24",
    "guests": "2 adults",
    "message": "Birthday celebration",
    "referral": "other",
    "sourceForm": "booking"
  },
  {
    "id": "b-20260424-rich-schones",
    "type": "booking",
    "name": "Rich Schones",
    "email": "schonesfamily@gmail.com",
    "phone": "+1 949-394-1213",
    "date": "2026-04-24T18:49:44.604Z",
    "arrival": "2026-09-18",
    "departure": "2026-09-24",
    "guests": "6 adults",
    "message": "Parents, 2 daughters and their husbands for my wifes birthday. Looking for price",
    "referral": "google",
    "sourceForm": "booking"
  },
  {
    "id": "c-20260424-val-kaye",
    "type": "contact",
    "name": "Val Kaye",
    "email": "val@sisterhoodtravels.com",
    "date": "2026-04-24T16:58:40.061Z",
    "message": "Hello, I am following up to my previous email for information please Val Kaye Travel Planner Sisterhood Travels",
    "sourceForm": "contact"
  },
  {
    "id": "b-20260424-erin-jones",
    "type": "booking",
    "name": "Erin Jones",
    "email": "erinj58@yahoo.com",
    "phone": "+1 470-460-0412",
    "date": "2026-04-24T06:14:57.611Z",
    "arrival": "2027-04-15",
    "departure": "2027-04-19",
    "guests": "14 adults",
    "message": "family vacation",
    "referral": "google",
    "sourceForm": "booking"
  },
  {
    "id": "c-20260421-val-kaye",
    "type": "contact",
    "name": "Val Kaye",
    "email": "val@sisterhoodtravels.com",
    "date": "2026-04-21T19:58:19.950Z",
    "message": "Hello- We are interested in a possible buyout of your location for a women's group trip in January, 2028, (possibly the last week in January. There are a lot of logistics and questions we have to see if this is the right fit for our tour and we have amany questions on pricing and what is included and what is not. Do. you have a person I can work with to coordinate with? Thank you Val Kaye Sisterhood Travels val@sisterhoodtravels.com",
    "sourceForm": "contact"
  },
  {
    "id": "c-20260420-lori-devine",
    "type": "contact",
    "name": "Lori Devine",
    "email": "lori@marallinace.org",
    "date": "2026-04-20T21:15:35.493Z",
    "message": "Hello, I am working with MarAlliance, and Canary Cove is listed as the preferred accommodations for our February trips. I am attempting to automate our system for reservations and payments by using the WeTravel platform. Is there someone I can email an invitation to? I also need to check availability and rates for Feb 20-27th 2027. Please feel free to reach out to me. I don't have much information in my notes. Thank you! Lori Devine Expeditions Coordinator",
    "sourceForm": "contact"
  }
];
