// Generated by the Canary Cove lead ingest. Do not edit by hand.

export type { Submission, SubmissionType } from "./submission-types";

import type { Submission } from "./submission-types";
import { recentSubmissions } from "./submissions-recent";
import { midASubmissions } from "./submissions-mid-a";
import { midBSubmissions } from "./submissions-mid-b";
import { oldASubmissions } from "./submissions-old-a";
import { oldBSubmissions } from "./submissions-old-b";

export const submissionImportSummary = {
  exportedAt: "2026-09-15T15:17:43.000Z",
  rawRows: 46,
  visibleRows: 24,
  filteredRows: 22,
  contactRows: 23,
  bookingRows: 23,
  excludedEmailCaptureRows: 2,
  reviewRows: 0,
  sourceFiles: [
    "Formspree API xvzarybk contact complete export",
    "Formspree API xqeqllek booking complete export"
  ]
} as const;

export const submissions: Submission[] = [
  ...recentSubmissions,
  ...midASubmissions,
  ...midBSubmissions,
  ...oldASubmissions,
  ...oldBSubmissions,
];
